// <auto-generated />
using System;
using DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

namespace DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200603211711_init_three")]
    partial class init_three
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Transactions", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("AgeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("C10101")
                        .HasColumnType("int");

                    b.Property<int?>("C10102")
                        .HasColumnType("int");

                    b.Property<int?>("C10103")
                        .HasColumnType("int");

                    b.Property<int?>("C10104")
                        .HasColumnType("int");

                    b.Property<int?>("C10105")
                        .HasColumnType("int");

                    b.Property<int?>("C10106")
                        .HasColumnType("int");

                    b.Property<int?>("C10107")
                        .HasColumnType("int");

                    b.Property<int?>("C10108")
                        .HasColumnType("int");

                    b.Property<int?>("C10109")
                        .HasColumnType("int");

                    b.Property<int?>("C10110")
                        .HasColumnType("int");

                    b.Property<int?>("C10111")
                        .HasColumnType("int");

                    b.Property<int?>("C10112")
                        .HasColumnType("int");

                    b.Property<int?>("C10113")
                        .HasColumnType("int");

                    b.Property<int?>("C10114")
                        .HasColumnType("int");

                    b.Property<int?>("C10115")
                        .HasColumnType("int");

                    b.Property<int?>("C10116")
                        .HasColumnType("int");

                    b.Property<int?>("C10117")
                        .HasColumnType("int");

                    b.Property<int?>("C10118")
                        .HasColumnType("int");

                    b.Property<int?>("C10119")
                        .HasColumnType("int");

                    b.Property<double?>("C10120")
                        .HasColumnType("float");

                    b.Property<int?>("C10201")
                        .HasColumnType("int");

                    b.Property<int?>("C10202")
                        .HasColumnType("int");

                    b.Property<int?>("C10203")
                        .HasColumnType("int");

                    b.Property<int?>("C10204")
                        .HasColumnType("int");

                    b.Property<int?>("C10205")
                        .HasColumnType("int");

                    b.Property<int?>("C10206")
                        .HasColumnType("int");

                    b.Property<int?>("C10207")
                        .HasColumnType("int");

                    b.Property<int?>("C10208")
                        .HasColumnType("int");

                    b.Property<int?>("C10209")
                        .HasColumnType("int");

                    b.Property<int?>("C10210")
                        .HasColumnType("int");

                    b.Property<int?>("C10211")
                        .HasColumnType("int");

                    b.Property<int?>("C10212")
                        .HasColumnType("int");

                    b.Property<int?>("C10301")
                        .HasColumnType("int");

                    b.Property<int?>("C10302")
                        .HasColumnType("int");

                    b.Property<int?>("C10303")
                        .HasColumnType("int");

                    b.Property<int?>("C10304")
                        .HasColumnType("int");

                    b.Property<int?>("C10305")
                        .HasColumnType("int");

                    b.Property<int?>("C10306")
                        .HasColumnType("int");

                    b.Property<int?>("C10307")
                        .HasColumnType("int");

                    b.Property<int?>("C10308")
                        .HasColumnType("int");

                    b.Property<int?>("C10401")
                        .HasColumnType("int");

                    b.Property<int?>("C10402")
                        .HasColumnType("int");

                    b.Property<int?>("C10403")
                        .HasColumnType("int");

                    b.Property<int?>("C10404")
                        .HasColumnType("int");

                    b.Property<int?>("C10405")
                        .HasColumnType("int");

                    b.Property<int?>("C10406")
                        .HasColumnType("int");

                    b.Property<int?>("C10407")
                        .HasColumnType("int");

                    b.Property<int?>("C10408")
                        .HasColumnType("int");

                    b.Property<int?>("C10409")
                        .HasColumnType("int");

                    b.Property<int?>("C10410")
                        .HasColumnType("int");

                    b.Property<int?>("C10501")
                        .HasColumnType("int");

                    b.Property<int?>("C10502")
                        .HasColumnType("int");

                    b.Property<int?>("C10503")
                        .HasColumnType("int");

                    b.Property<int?>("C10504")
                        .HasColumnType("int");

                    b.Property<int?>("C10505")
                        .HasColumnType("int");

                    b.Property<int?>("C10506")
                        .HasColumnType("int");

                    b.Property<int?>("C10507")
                        .HasColumnType("int");

                    b.Property<int?>("C10508")
                        .HasColumnType("int");

                    b.Property<int?>("C10509")
                        .HasColumnType("int");

                    b.Property<int?>("C10510")
                        .HasColumnType("int");

                    b.Property<int?>("C10511")
                        .HasColumnType("int");

                    b.Property<int?>("C10512")
                        .HasColumnType("int");

                    b.Property<int?>("C10601")
                        .HasColumnType("int");

                    b.Property<int?>("C10602")
                        .HasColumnType("int");

                    b.Property<int?>("C10603")
                        .HasColumnType("int");

                    b.Property<int?>("C10604")
                        .HasColumnType("int");

                    b.Property<int?>("C10605")
                        .HasColumnType("int");

                    b.Property<int?>("C10606")
                        .HasColumnType("int");

                    b.Property<int?>("C10607")
                        .HasColumnType("int");

                    b.Property<int?>("C10608")
                        .HasColumnType("int");

                    b.Property<int?>("C10609")
                        .HasColumnType("int");

                    b.Property<int?>("C10610")
                        .HasColumnType("int");

                    b.Property<int?>("C10611")
                        .HasColumnType("int");

                    b.Property<int?>("C10612")
                        .HasColumnType("int");

                    b.Property<int?>("C10701")
                        .HasColumnType("int");

                    b.Property<int?>("C10702")
                        .HasColumnType("int");

                    b.Property<int?>("C10703")
                        .HasColumnType("int");

                    b.Property<int?>("C10704")
                        .HasColumnType("int");

                    b.Property<int?>("C10705")
                        .HasColumnType("int");

                    b.Property<int?>("C10706")
                        .HasColumnType("int");

                    b.Property<int?>("C10707")
                        .HasColumnType("int");

                    b.Property<int?>("C10708")
                        .HasColumnType("int");

                    b.Property<int?>("C10801")
                        .HasColumnType("int");

                    b.Property<int?>("C10802")
                        .HasColumnType("int");

                    b.Property<int?>("C10803")
                        .HasColumnType("int");

                    b.Property<int?>("C10804")
                        .HasColumnType("int");

                    b.Property<int?>("C10805")
                        .HasColumnType("int");

                    b.Property<int?>("C10806")
                        .HasColumnType("int");

                    b.Property<int?>("C10807")
                        .HasColumnType("int");

                    b.Property<int?>("C10901")
                        .HasColumnType("int");

                    b.Property<int?>("C11001")
                        .HasColumnType("int");

                    b.Property<int?>("C11002")
                        .HasColumnType("int");

                    b.Property<int?>("C11003")
                        .HasColumnType("int");

                    b.Property<int?>("C11004")
                        .HasColumnType("int");

                    b.Property<int?>("C11005")
                        .HasColumnType("int");

                    b.Property<int?>("C11006")
                        .HasColumnType("int");

                    b.Property<int?>("C11101")
                        .HasColumnType("int");

                    b.Property<int?>("C11201")
                        .HasColumnType("int");

                    b.Property<int?>("C11202")
                        .HasColumnType("int");

                    b.Property<int?>("C11203")
                        .HasColumnType("int");

                    b.Property<int?>("C11204")
                        .HasColumnType("int");

                    b.Property<int?>("C11205")
                        .HasColumnType("int");

                    b.Property<int?>("C11301")
                        .HasColumnType("int");

                    b.Property<int?>("C11401")
                        .HasColumnType("int");

                    b.Property<int?>("C11501")
                        .HasColumnType("int");

                    b.Property<int?>("C201")
                        .HasColumnType("int");

                    b.Property<int?>("C202")
                        .HasColumnType("int");

                    b.Property<int?>("C203")
                        .HasColumnType("int");

                    b.Property<int?>("C204")
                        .HasColumnType("int");

                    b.Property<int?>("C205")
                        .HasColumnType("int");

                    b.Property<int?>("C206")
                        .HasColumnType("int");

                    b.Property<int?>("C207")
                        .HasColumnType("int");

                    b.Property<int?>("C208")
                        .HasColumnType("int");

                    b.Property<int?>("C209")
                        .HasColumnType("int");

                    b.Property<int?>("C210")
                        .HasColumnType("int");

                    b.Property<int?>("C211")
                        .HasColumnType("int");

                    b.Property<int?>("C212")
                        .HasColumnType("int");

                    b.Property<int?>("C213")
                        .HasColumnType("int");

                    b.Property<int?>("C214")
                        .HasColumnType("int");

                    b.Property<int?>("C215")
                        .HasColumnType("int");

                    b.Property<int?>("C216")
                        .HasColumnType("int");

                    b.Property<int?>("C217")
                        .HasColumnType("int");

                    b.Property<int?>("C301")
                        .HasColumnType("int");

                    b.Property<int?>("C302")
                        .HasColumnType("int");

                    b.Property<int?>("C303")
                        .HasColumnType("int");

                    b.Property<int?>("C304")
                        .HasColumnType("int");

                    b.Property<int?>("C305")
                        .HasColumnType("int");

                    b.Property<int?>("C306")
                        .HasColumnType("int");

                    b.Property<string>("C401")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C402")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C403")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("C404")
                        .HasColumnType("int");

                    b.Property<int?>("C405")
                        .HasColumnType("int");

                    b.Property<string>("C406")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("C407")
                        .HasColumnType("int");

                    b.Property<int?>("C408")
                        .HasColumnType("int");

                    b.Property<int?>("C409")
                        .HasColumnType("int");

                    b.Property<int?>("C410")
                        .HasColumnType("int");

                    b.Property<string>("C411")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C501")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C502")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C503")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("C504")
                        .HasColumnType("int");

                    b.Property<int?>("C505")
                        .HasColumnType("int");

                    b.Property<string>("C601")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C602")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("C603")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geography");

                    b.Property<DateTime?>("Lastupdatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vcgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DAL.Entities.Txns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AmtofMilkdp")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreedGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Revenue")
                        .HasColumnType("float");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Txns");
                });

            modelBuilder.Entity("DAL.Entities.Txns", b =>
                {
                    b.HasOne("DAL.Entities.Transactions", "FarmerList")
                        .WithMany("Txns")
                        .HasForeignKey("TransactionId");
                });
#pragma warning restore 612, 618
        }
    }
}
